### ISSUE TITLE
Centre-align text

### ISSUE THREAD

**Issue by bhattabhi013** [TheGuyDangerous/Voicerra#7]
Centre align the text here.

Screenshot:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/47862474/197276043-e8bc0b05-7259-454f-94e1-4903dec2e4a7.png">

**Comment by mnomanmemon** [comment]
Hi @TheGuyDangerous , can you assign this to me?

**Comment by TheGuyDangerous** [comment]
No need @mnomanmemon and @bhattabhi013 , I've fixed the issue in the latest build.
Although , you both can do a UI overhaul by creating the issue and getting it assigned under hacktoberfest , if you want.
I'll need to see the changes (screenshots) of the screen/parts you could work on.

**Comment by mnomanmemon** [comment]
@TheGuyDangerous , Can you show the screenshots of the screens on which I could work?

**Comment by TheGuyDangerous** [comment]
@mnomanmemon  I'm currently working Fixing the Ui of the app to be more minimal.
Absample screenshot with the color pallette chosen is uploaded below 👇 - 
![Screenshot_20221023_203833](https://user-images.githubusercontent.com/78858516/197399938-8f8f1f5e-9837-4365-9e05-dec9d19866fd.jpg)
The ui would contain more neumorphic elements and glassmorphic elements in the future builds.
If you could help out in creating some minimal layouts following the new colour Pallette (yellow , Color(0xFF55E5B1) and white) it would be so helpful.
you could remake Screens suxh as contact page , translate page and other such pages (given that you open an issue first).
